// Lista de segmentos disponíveis (mesma do mercado SaaS de encartes).
// Fica num módulo próprio (sem componente React) pra ser reusada tanto pelo
// modal "Meus Interesses" quanto pelo Painel Admin (ranking de interesses) sem
// quebrar o Fast Refresh do Vite.
export const SEGMENTOS = [
  { id: 'todos',            nome: 'Todos os segmentos',        especial: true },
  { id: 'eventos',          nome: 'Eventos Regionais' },
  { id: 'supermercado',     nome: 'Supermercado' },
  { id: 'acougue',          nome: 'Açougue' },
  { id: 'hortifruti',       nome: 'Hortifrúti' },
  { id: 'farmacia',         nome: 'Farmácia' },
  { id: 'construcao',       nome: 'Material para Construção' },
  { id: 'bebidas',          nome: 'Distribuidora de Bebidas' },
  { id: 'autopecas',        nome: 'Autopeças' },
  { id: 'fastfood',         nome: 'Fast Food' },
  { id: 'academia',         nome: 'Academia' },
  { id: 'barbearia',        nome: 'Barbearia' },
  { id: 'escola',           nome: 'Escola' },
  { id: 'imobiliaria',      nome: 'Imobiliária' },
  { id: 'livraria',         nome: 'Livraria' },
  { id: 'sorvetes',         nome: 'Sorvetes' },
  { id: 'cosmeticos',       nome: 'Cosméticos' },
  { id: 'cimed',            nome: 'CIMED' },
  { id: 'esportivos',       nome: 'Artigos Esportivos' },
  { id: 'concessionaria-carros', nome: 'Concessionaria de Carros' },
  { id: 'concessionaria-motos',  nome: 'Concessionaria de Motos' },
  { id: 'baterias',         nome: 'Baterias Elétricas' },
  { id: 'moveis',           nome: 'Móveis e Eletro' },
  { id: 'motopecas',        nome: 'Moto Peças' },
  { id: 'bebes',            nome: 'Bebês' },
  { id: 'pisos',            nome: 'Pisos e Revestimentos' },
  { id: 'tintas',           nome: 'Tintas e Ferramentas' },
  { id: 'ferragens',        nome: 'Ferragens' },
  { id: 'tubos',            nome: 'Tubos e Conexões' },
  { id: 'maquinas',         nome: 'Maquinas e Ferramentas' },
  { id: 'calcados',         nome: 'Calçados' },
  { id: 'roupas',           nome: 'Roupas e Acessórios' },
  { id: 'oticas',           nome: 'Óticas' },
  { id: 'informatica',      nome: 'Informática' },
  { id: 'vinhos',           nome: 'Vinhos' },
  { id: 'comida-japonesa',  nome: 'Comida Japonesa' },
  { id: 'restaurante',      nome: 'Restaurante' },
  { id: 'hamburgueria',     nome: 'Hamburgueria' },
  { id: 'salgadaria',       nome: 'Salgadaria' },
  { id: 'agua-gas',         nome: 'Água e Gás' },
  { id: 'brinquedos',       nome: 'Brinquedos' },
  { id: 'floricultura',     nome: 'Floricultura e Jardim' },
  { id: 'frios',            nome: 'Frios e Laticínios' },
  { id: 'padaria',          nome: 'Padaria' },
  { id: 'papelaria',        nome: 'Papelaria' },
  { id: 'naturais',         nome: 'Produtos Naturais' },
  { id: 'piscina',          nome: 'Produtos para Piscina' },
  { id: 'agropecuaria',     nome: 'Agropecuária' },
  { id: 'petshop',          nome: 'Pet Shop' },
  { id: 'utilidades',       nome: 'Utilidades Domésticas' },
  { id: 'suplementos',      nome: 'Suplementos Alimentares' },
  { id: 'eletricos',        nome: 'Materiais Elétricos' },
];
